### ISSUE TITLE
WorkflowFragment using deprecated onActivityCreated()

### ISSUE THREAD

**Issue by ychescale9** [square/workflow#1122]
`WorkflowFragment` is starting workflow in `onActivityCreated()` which is deprecated in [AndroidX Fragment 1.3.0](https://android-review.googlesource.com/c/platform/frameworks/support/+/1189651).

Should we move the initialization to `onViewCreated()` instead?

I'm ready to send a PR:)

**Comment by zach-klippenstein** [comment]
We should definitely not be relying on deprecated APIs. I don't think there's any logic in that method that actually relies on that particular lifecycle event, but @rjrjr should confirm. If there is, we can use the onAttach LifecycleObserver trick mentioned in that PR, otherwise we can probably do what you've proposed. 

If you want to submit a PR, that would be great! I would hold off for Ray's confirmation though to make sure you're not doing wasted work. Thanks for filing!

**Comment by rjrjr** [comment]
Doing it in `onViewCreated` would get view persistence out of order:

```
     * Called immediately after {@link #onCreateView(LayoutInflater, ViewGroup, Bundle)}
     * has returned, but before any saved state has been restored in to the view.
```

`onViewStateRestored` looks like a better proxy.
