### ISSUE TITLE
Multiple output events; purely functional onReact() method

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#133]
cc @loganj @steveinflow @zach-klippenstein @mbrubin56 @timdonnelly 

Two changes. 

Small one: allow a workflow to emit multiple output events, instead of one result value. That could be as simple as

```kotlin
EnterState<S, O>(
  state: S,
  output: O? = null
)

```

Big one:  solve all of our lifecycle management rough edges by returning the select builder from onReact. Gives WorkflowPool enough information to know exactly what state we're in, and therefore to tear down any spun up services when we leave it. abandon() calls all go away.

```kotlin
fun onReact(state: S) : ResponseMap<S, E, O> {
  return responseMap {
    state.childHandle to { workflowUpdate : WorkflowUpdate<...> -> 
      when (workflowUpdate) {
        // Some discussion of finding a way to pass these in as separate
        // functions, to leave Logan a hook to replace the Running case
        // with something automatic.
        is Running -> { EnterState(...) }
        is Output -> ...
        is Finished -> ...
      }
    }
    worker to { result -> ... }
    event to { event -> when(state) { ... }}
  }
}
```

Some talk also about moving further, drop nested state structs and make live inside workflow, api around mapping workflow handles to their current state. But the above is a more incremental change that allows Renderers and Snapshot code to stay as it is now. And maybe its simplicity is the best stopping point anyway.

![img_20190123_152302](https://user-images.githubusercontent.com/1884445/51645319-9b875000-1f28-11e9-8f44-60a20b2bd217.jpg)

**Comment by loganj** [comment]
+1 to just dropping the interfaces. Excited to see less stuff.

Re going further: definitely let's make the incremental change now, but should seriously consider going further and relieving the user of the state aggregation work as an immediate followup. It's so mechanical I wrote a class that handles it -- pretty clear indication that the library could take care of it for you. And if not now, when?

**Comment by zach-klippenstein** [comment]
I think we should provide that as an option in the core library, but I
don't want to make it the only way to compose.

Can you post a PR to add it to the `workflow-core` module?

**Comment by zach-klippenstein** [comment]
I think we should provide that as an option in the core library, but I
don't want to make it the only way to compose.

Can you post a PR to add it to the `workflow-core` module?

**Comment by zach-klippenstein** [comment]
Some thoughts:
* `WorkflowPool` → `StateMachineHost`
* A *`StateMachineHost` contains a `StateMachine`* (`typealias = (State) -> Behavior`).
* *You create a `StateMachineHost`* by passing it a `(StateMachineRegistrar) -> StateMachine`
`StateMachineRegistrar` is an interface that allows child state machines’ launchers to be registered (today’s `WorkflowPool.register()`, but as a separate interface).
* *`Behavior`* is an immutable type that describes what events to handle, what child state machines should be running, what workers to run, etc, and what states/outputs to emit as a result. It’s analogous to a combination of `EventSelectBuilder` and the event channel. Might make more sense for the statemachine function to actually be a `BehaviorBuilder.(State) -> Unit` (like my above sketch) just to make it simpler to use and harder to abuse.
* *`StateMachineHost` also contains* the live state about what workers are actually running, what child state machines are running (as references to their `StateMachineHost`s).
* *`StateMachineHost` performs the state machine event loop*, a job currently performed by the intermediate layer between `Reactor` and `Workflow`

And some rough code sketches I just want to get down so I don't forget:
sealed class Reaction2<out S : Any, out O : Any> {
```kotlin
  data class EnterState<S>(
    val newState: S
  ) : Reaction2<S, Nothing>()

  /**
   * Emits [output], then enters state [thenEnterState].
   * If [thenEnterState] is `null`, stays in the same state.
   *
   * E.g.
   *
   * return Output(someOutput,
   *     thenEnterState = MyNewState(…))
   * 
   */
  data class Output<S, O>(
    val output: O,
    val thenEnterState: S? = null
  ) : Reaction2<S, O>()
}
```

I think we can clean up how we handle hot observables too. Elm uses the concept of "subscriptions" - every time your state function returns, you can indicate what subscriptions you want. That would fit naturally in the BehaviorBuilder. It's effectively the same thing as what we're doing with workers now, and what we were _trying_ to do with hot observables initially, but couldn't because we had to actually subscribe and unsubscribe to the source on every loop. In the new world, with the host managing ALL the things, we can actually do that properly.

We could still support subscribing to hot observables in the launcher, but that always has felt a little awkward to me and is super not discoverable. It also requires the boilerplate of mapping to events - something you don't need to do if you're "subscribing" directly in the state transition function.

I think we'll want to pull out a more abstract "idempotence key" as well - right now, the tuple of `Launcher.Type` and `name` serve as an idempotence key for workers and workflows, but we can just add an explicit, `Any`-typed idempotence key parameter to support both this and other keys. E.g. if you just want to listen to a `Single`, you don't need to wrap it in a worker, just use the `Single` instance itself as the idempotence key. The state machine host compares idempotence keys to figure out which subscriptions should be stable across state transitions. For workflows, the idempotence key is just the `Id`.  We'd still need to wrap observables with something lazy, but having an explicit idempotence key lets you have multiple observables of the same type without having to explicitly name them or have them accidentally conflict.

If there's a use case that really only cares about the overall state machine's lifecycle (eg some reader workflows), that's easy to solve too: Since StateMachineHosts will be nested, each one has a coroutine `Job`. When the state machine terminates, the job's children are cancelled. When the state machine is cancelled, the job is cancelled. The job is passed (probably as a coroutine scope) to the Launcher function. Any lifetime-aware logic can use that scope to do whatever it needs to do.

Some more sketching:
```kotlin
typealias StateMachineLauncher = (StateMachineScope) -> StateMachine
typealias StateMachine = BehaviorBuilder.(S) -> Unit

interface StateMachineScope : CoroutineScope {
  fun register(StateMachineLauncher)
}

interface BehaviorBuilder {
  fun onStateMachineUpdate(Handle, (Update)->Reaction)
  fun onAwait(()->Deferred, idemKey: Any, (T)->Reaction)
  fun onReceive(()->ReceiveChannel, idemKey: Any, (T)->Reaction)
}
fun BehaviorBuilder.onAwait(d: Deferred, idemKey: Any=d, (T)->Reaction) = onAwait({d}, idemKey, block)
// Ditto for channel

// In Rx2 module:
fun BehaviorBuilder.onSuccess(s:Single, idemKey: Any=s, (T)->Reaction) = onAwait({s.toDeferred()}, idemKey, block)
fun BehaviorBuilder.onNext(o: Observable, idemKey=o, (T)->Reaction) = onReceive({o.openSubscription()}, o, block)```
```
