### ISSUE TITLE
Workflows started with setContentWorkflow may drop early output emissions.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#430]
I'm not thrilled with this extension method any more, but have no change to suggest for this PR. I'll follow up after you merge.

_Originally posted by @rjrjr in https://github.com/square/workflow/pull/426_

**Comment by rjrjr** [comment]
More thoughts on this:

 * Worst problem is it's difficult / impossible to receive all output events when you're setting things up from onCreate in an Activity or Fragment
 * Surprising that `setContentWorkflow()` now returns an object whose `start()` method must be called. Should just drop the extensions, they're too clever.
 * Confusing that workflow is provided on every call to `setContentWorkflow`. It's only needed the first time, should make that a factory lambda

**Comment by zach-klippenstein** [comment]
This issue name is obsolete: `WorkflowRunner` no longer has a start method, it starts the workflow host lazily when one of the outputs is subscribed to, like it did before. 

As for outputs, we should hook into the lifecycle of whatever is creating/retrieving the workflow runner (activity or fragment) and either buffer or pause (via backpressure) the emission of outputs when the lifecycle owner isn't active. And since that caller will be subscribing to outputs from an activity or component, the subscription will likely close over that object and we should be careful to not invoke it in a bad state.

**Comment by zach-klippenstein** [comment]
I updated the isuse name, removing from 0.18 milestone.

**Comment by rjrjr** [comment]
As part of the discussion behind #439, we're realizing that this is a pretty easy (and natural) problem for WorkflowRunner to solve. It's job is to ensure that outputs are buffered until someone is subscribed to receive them.

At the same time, we should probably replace its rendering and outputs Rx Observables with LiveData properties.

**Comment by rjrjr** [comment]
@zach-klippenstein I've added this back to the 0.18.0 milestone. Suddenly it seems like we have the complete pictures, seems like we should implement it all at once and be sure that it works.
