### ISSUE TITLE
Delete legacy code

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#548]
It's well past time.

**Comment by zach-klippenstein** [comment]
We're not going to be able to delete this anytime soon, and that should definitely not block 1.0. We could pull them out into a separate repo, but that would just make more work for us. We could leave them here and stop releasing new artifacts for them, but we might run into issues as they fall behind on dependencies like coroutines and kotlin. We could just keep them going publishing 0.x releases, but it's already too late for that, since we pushed the 1.0.0-alpha.1 release. We could keep them in alpha, even after the other artifacts graduate to beta/release, but we'll need to do some surgery on our build scripts.

@rjrjr WDYT?
