### ISSUE TITLE
Android EditText crashes on fast typing

### ISSUE THREAD

**Issue by 0legg** [square/workflow#627]
Steps to reproduce:
- Have EditText on your screen
- Set TextWatcher on it to pass data back to workflow via lambda
- Send workflow action to the sink from this lambda
- Type fast into the EditText

App crashes pretty fast on trying to send action to stale sink.

**Comment by zach-klippenstein** [comment]
This is happening because we haven't fixed #541 yet. It's the same issue as #348.

**Comment by zach-klippenstein** [comment]
You can work around this for now the same way that the TODO sample app does it: 
https://github.com/square/workflow/blob/8c10f6069915310600fe771f224d668000fadaa2/kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoEditorWorkflow.kt#L100-L110

**Comment by zach-klippenstein** [comment]
I've never been happy with #541 as a fix for this. It's a hack because it breaks the "synchronous render pass" model and it only works if the `WorkflowAction`s don't close over anything else from the render pass. If that's not the case, and it's very easy to do that (and can be useful), then some actions will be executed with invalid state. You lose a lot of the advantages of having a synchronous render pass, but only in this case and there's nothing warning you if you do something bad.

I think there are a couple solutions that could be a better fix. The first is simpler and easy to implement as needed, but it only works for this case, with `TextView`s.

### 1. Conflation

This approach realizes that, since the full contents of the text view are being sent each time, we're not really sending "events" we're synchronizing state between two independent state machines. So we don't actually need to send _every_ state if a bunch of state changes happen very quickly, which is what causes this issue.

This solution ignores text changed events if they come in to fast, and will just wait for the next valid event handler to be passed in to send the next event. An object similar to the following can be stored in the view tag:

```kotlin
class WorkflowTextEventRelay(private val textView: EditText) {

  data class WorkflowText(
    val text: String?,
    val onTextChanged: (String) -> Unit
  )

  private var lastText: String? = null
  private var listener: TextWatcher? = null

  fun update(text: WorkflowText) {
    if (lastText != text.text) {
      // This is a fresh rendering from the workflow, but the workflow's internal text is out
      // of sync – immediately send the current value to the workflow.
      lastText = text.text
      text.onTextChanged(text.text)
    } else {
      // The text matches, which means the user hasn't typed anything since the last rendering
      // and the workflow is in sync - acquiescence.
      // We don't need to tell the workflow anything until the next text change from the user.
      listener = SimpleWatcher { newText ->
        textView.removeTextChangedListener(listener)
        listener = null
        lastText = newText
        text.onTextChanged(newText)
      }
      textView.addTextChangedListener(listener)
    }
  }
}
```

### 2. Proper queuing

If the workflow wants to handle every single update, then the above solution doesn't work. It is a fix for the text case specifically because we happen to be sending the full state back to the workflow every time, but if we need to handle UI events that only send deltas, it won't work since some deltas would be dropped. Instead, we need to queue the updates somehow. Issue #541 proposes queuing the actions themselves in the runtime, but this is a bad, hacky idea for reasons listed above. This is a more involved solution than conflation, but is a better fix than #541 and doesn't require any changes to the runtime itself.

This approach introduces a special helper workflow along with its own `TextRendering` rendering type, as well as a helper for EditText. It effectively tracks a "connection" between the text view instance and the workflow session that is handling updates. When a text view is shown a `TextRendering`, that rendering indicates which workflow it was from. If the text view is already "connected" to that workflow, it just updates its text. If it's not connected to that workflow yet (i.e. first bind, or a recycler view moving things around), it immediately sends an event to the `TextRendering` containing a stream of its text change events. This establishes a "connection" with the underlying workflow session. The text change worker is probably just backed by a channel that is saved in the view helper. The view _always_ has a `TextWatcher` registered that just feeds events into this channel. If multiple text events are sent for a single render pass, it's fine – since the connection is already established, the events themselves (not the `WorkflowAction`s) get queued up on the channel. And since workers support backpressure, as long as the workflow session that currently connected to the view stays alive, it will eventually get around to processing the events.

Here's a rough sketch:

```kotlin
object TextWorkflow : StatefulWorkflow<String, State, String, TextRendering>() {
  
  data class State(
    val id: UUID = UUID.random(),
    val textChanges: Worker<String>? = null
  )

  data class TextRendering(
    val workflowId: UUID,
    val text: String,
    val onBind: (Worker<String>) -> Unit
  )

  sealed class Action : WorkflowAction<State, String> {
    data class Bind(val worker: Worker<String>) : Action()
    data class TextChanged(val text: String) : Action()

    fun apply(…) = when(this) {
      is Bind -> {
        state = state.copy(textChanges = this.worker)
        return null
      }
      is TextChanged -> {
        return this.text
      }
    }
  }

  fun initialState(…) = State()

  fun render(…) {
    val sink = context.makeActionSink<Action>()

    state.textWorker?.let { textWorker ->
      context.runningWorker(textWorker) { text -> TextChanged(text) }
    }

    return TextRendering(
      workflowId = state.id,
      text = props,
      onBind = { worker -> sink.send(Bind(worker)) }
    )
  }
```

```kotlin
class WorkflowTextHelper(private val textView: TextView) {

  private var currentWorkflowId: UUID? = null
  private val changes = Channel<String>(capacity = UNLIMITED)
  
  init {
    val listener = SimpleListener { text -> changes.offer(text) }
    textView.addTextChangedListener(listener)
  }

  fun update(rendering: TextRendering) {
    textView.text = rendering.text
    if (rendering.workflowId != currentWorkflowId) {
      currentWorkflowId = rendering.workflowId
      // TODO probably need to create a new channel here every time so that if the old workflow
      // is still running it doesn't get any of our events – although that shouldn't happen since it's
      // either also just bound to or about to be bound to another view, or gone completely.
      rendering.onBind(changes.asWorker())
    }
  }
}
```

Note that this sketch is specific to text but those events could be anything, including deltas. The workflow ID machinery is there so that if the same `TextView` instance is asked to show a rendering that actually comes from a completely different workflow (e.g. the view is in a `RecyclerView` and is being rebound to a completely unrelated source), it knows that it needs to establish a new connection. It would be completely unnecessary without the `RecyclerView` case. On the workflow side, a workflow that needs to render multiple text fields (potentially in a `RecyclerView`) just needs to ensure it provides keys when rendering children so that they are unique (the runtime will crash if you don't anyway), and then just render a `TextWorkflow` for every field it needs to show:

```kotlin
fun render(…) {
  …

  return MyComplexRendering(
    nameField = context.renderChild(TextWorkflow, state.name, "name") { … },
    emailField = context.renderChild(TextWorkflow, state.email, "email") { … },
    addressField = context.renderChild(TextWorkflow, state.address, "address") { … },
    …
  )
}
```

**Comment by 0legg** [comment]
TBH I feel we have a bigger problem if rendering EditText comes with such non-trivial solution. As a local workaround I'm doing one-way sync (view sets it state to workflow, relying no one outside is modifying it) when view is focused, and syncing from workflow to view when it's out of focus.

**Comment by zach-klippenstein** [comment]
Yes, there is a bigger problem that I'm trying to figure out right now – why are we getting multiple events in the same main event loop iteration, even with async diffing turned off. However, even if we figure that out, this situation will still occur if any `RecyclerView` is updated with async diffing.

Rendering events were designed to be synchronous because that's how UI frameworks tend to work, at least most of the time. If it turns out that simplifying assumption is more wrong than it is right, we might need to make more drastic changes.

**Comment by zach-klippenstein** [comment]
Ok so no reason to panic just yet – the extra weird behavior was just because the subscription to workflow events was using a redundant `observeOn` which was trampolining all workflow updates to the next main loop iteration.

However this issue still legitimately occurs for `TextView`s that are in `RecyclerView`s that are bound asynchronously (e.g. `DiffUtil` is used on a background thread). To fix this, I'm going to go with the conflation approach above, since it's the simplest.

**Comment by zach-klippenstein** [comment]
The 2nd approach [above](https://github.com/square/workflow/issues/627#issuecomment-536335124) is over-engineered. It also doesn't work if the `onBind` call happens to trigger a workflow update while the `RecyclerView` is rendering.

### 3. Proper queuing with a custom event channel

#### Event queueing

A more straightforward approach is to have the `TextWorkflow` publish an event handler like normal, but instead of backing that handler with a `Sink`, have the `TextWorkflow`'s state hold onto a private `Channel` that can be buffered, effectively duplicating the sink pattern but with entirely custom behavior. Since the same channel is used for all events, the event handler never becomes stale. And since events are just being delivered through the usual worker machinery, we don't need to violate any guarantees about what state/props can be closed over.

#### State machine synchronization

Using a custom channel/`Worker` to back the event handler solves the queueing problem. However for `EditText`s there is a second problem, which is ensuring that rapid changes to the text contents don't get clobbered by out-of-date renderings from a workflow that is churning through queued events one-by-one. To solve this, we can use a simple monotonically-increasing sequence number in both the view helper and the workflow('s state). In the view helper, it gets incremented whenever a text change event is sent. In the workflow, it gets incremented whenever a text change event is handled (by the `WorkflowAction` that handles the event worker's outputs). The workflow then sends its current sequence number down with the rendering, and the view helper can compare with its own: if the workflow's sequence number is smaller, that means the rendering is in response to an old event, and there are more events left in the queue that will be imminently processed – in this case, don't set the text on the view because the workflow is behind. If the sequence number matches, the workflow is up-to-date and we can update the text from the workflow again. The view helper also needs to know when the workflow backing it changes, because it needs to reset its sequence number to the new workflow's. This can be done similar to the queueing solution above by using some sort of token unique to the backing workflow's session.

**Comment by zach-klippenstein** [comment]
Actually this is conceptually very similar to what swift is doing (I don't think swift actually buffers, just allows reusing sinks - I'm not sure how it handles backpressure), but implemented on top of the library instead of built in. 

I realized that our current event sink mechanism could be implemented on top of the library in almost the exact same way - building it in is just an optimization at this point.

**Comment by zach-klippenstein** [comment]
After #742 and demonstrated in #719, this seems to work fine on master now.
