### ISSUE TITLE
Is Reactor.doLaunch too opinionated about dispatchers?

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#75]
Currently, it forces the `Unconfined` dispatcher. `Reactor`s can override this by using something like `withContext` if they actually care. The reason for this is that most reactors shouldn't care about what dispatcher they're running on (if they do, they are probably performing side effects and that's a smell). 

However, this is surprising behavior since no other coroutine functions explicitly ignore the dispatcher from the passed-in context. Additionally, `withContext` is optimized to effectively no-op when the context isn't actually different.

There are three paths forward:
1. **No change.** Passed-in context is always ignored, `onReact` must use `withContext` if it cares (which it shouldn't). This is nice because the extra verbosity makes it more obvious that it's a smell, however since it's so surprising that the context's dispatcher is being ignored in the first place, this could be a footgun.
2. **`doLaunch` continues to use `Unconfined` internally, but invokes `onReact` on the passed-in dispatcher.** This removes the surprise, but feels a little over-engineered. Not sure if it's actually important that internal `doLaunch` code runs on `Unconfined`.
3. **No special dispatcher handling.** This is what most of the coroutine builders do, and probably makes the most sense until proven otherwise. Then the only question left is what the default dispatcher should be if none is passed in:
    1. `EmptyCoroutineContext` – Again the standard, but will default the dispatcher to `Dispatchers.Default` which is unnecessary (`doLaunch` isn't doing much work of its own).
    2. `Unconfined` – Reasonable default for glue code, but may be surprising for `onReact`.

**Comment by rjrjr** [comment]
Of the people you pinged I'm probably the least qualified to respond, so I'll ignore that and answer anyway.

I definitely gravitate to option 3, since it involves the least departure from standard co-routine practice. 

Between your options **i** (default to `EmptyCoroutineContext` like usual, and don't prematurely optimize `doLaunch`), and **ii** (default to `Unconfined`, since that's been working okay so far, and is likely the 99% case), **ii** sounds like the right thing. I'm less confident there, but it seems to strike a balance: it does the not-quite-normal-but-right-for-reactors thing that we're already doing, while deviating from standard practice in as minimal a way as possible.

One question: is this difficulty a sign that forcing `doLaunch` and `onReact` to share a single dispatcher is a mistake?

**Comment by zach-klippenstein** [comment]
> is this difficulty a sign that forcing doLaunch and onReact to share a single dispatcher is a mistake?

I mean, that's basically the heart of the question I'm trying to answer. 

Since the `doLaunch` machinery doesn't care, I don't think it makes sense to put the effort in to avoid dispatch unless we can prove there's actually a benefit to doing so.

**Comment by zach-klippenstein** [comment]
Being addressed in the rewrite.
