### ISSUE TITLE
renderTester with default initialState does not allow RenderTester to infer state types

### ISSUE THREAD

**Issue by kirillzh** [square/workflow#856]
When verifying action result I would like to make assertions against my state:
```kotlin
someStatefulWorkflow.renderTester(props = someProps) // note that initialState is not passed
    .render { it.doSomething() }
    .verifyActionResult { newState, output -> // newState is of type of Any?
     assertThat(newState.someValue).isEqualTo(0)
    }
```
This does not work because used `renderTester` with default `initialState` is a `Workflow` extension, not `StatefulWorkflow` extension. We could fix this by introducing two `renderTester` extensions, for `StatelessWorkflow` and `StatefulWorkflow` instead of one generic function.

**Comment by zach-klippenstein** [comment]
I would prefer tests be explicitly about state whenever possible, since it makes tests less brittle (they're not testing `initialState` as well) and easier to read - the initial state is defined explicitly in the test and you don't have to go searching far for it. The only reason the default overload is defined for stateless workflows is because the state type isn't known. This function should probably only be defined on `StatelessWorkflow` directly since it doesn't make much sense to "test" something that doesn't inherit from one of those two abstract classes.

Is there any particular reason you want to call your workflow's `initialState` method in this test?

**Comment by zach-klippenstein** [comment]
Closing as wont fix because the API is intentional, as discussed in the previous comment.
